### ISSUE TITLE
Feature: integrate Spotify API for playlists retrieval

### ISSUE THREAD

**Issue by dk-a-dev** [IEEE-VIT/playtify#12]
### Description:
Integrate the Spotify API into the Playtify app to fetch playlists from a specific category (e.g., "Pop," "Rock," "Chill"). This integration will allow the app to access and display Spotify playlists within the chosen category.

### Tips for the issue:
- Set up Spotify API integration in the Playtify project
- Implement a function to retrieve playlists from a specified category

### To do:
- [x] Ask us to assign the issue
- [x]  Once the issue is assigned, you can start working on it
- [x]  Create a PR

### Resources:
- [pub.dev/spotify_sdk](https://pub.dev/packages/spotify_sdk)

### Note:
The task is **assigned to contributors on a first-come, first-serve basis**, and the contributor has to **report progress every 3 days** to ensure active development on the tasks. If you need any help feel free to tag and message

**Comment by RitwikSingh28** [comment]
@dk-a-dev 
Please assign me this issue

**Comment by dk-a-dev** [comment]
You can work on this now @RitwikSingh28

**Comment by RitwikSingh28** [comment]
@dk-a-dev 

## Problem Encountered:
The use of [pub.dev/spotify_sdk](https://pub.devHTTP/packages/spotify_sdk) requires the user to have the Spotify app installed on their device. 

## Proposed Approach: 
Since we only need to fetch the playlist from a specific genre, we can:
* Use Spotify Web API, instead of `spotify_sdk`
* Authenticate via OAuth2 using [flutter_web_auth](https://pub.dev/packages/flutter_web_auth)
* Use `http` package to send **HTTP** requests to the Spotify Web API

## Advantage: 
**Dependency on presence of Spotify app removed**

Please let me know your thoughts :thought_balloon:

**Comment by dk-a-dev** [comment]
@RitwikSingh28 i agree with ur approach, good work on researching stuff , I approve u can work

**Comment by dk-a-dev** [comment]
@RitwikSingh28 whats the status of issue buddy

**Comment by RitwikSingh28** [comment]
> @RitwikSingh28 whats the status of issue buddy

@dk-a-dev 
I have been working on integrating the Spotify API, and have made the following progress. 

### Task List
- [x] Registered app on Spotify Dev
- [x] Authorization Code Flow integrated
- [ ] Need to integrate Playlist retrieval by `genre` or `category`

### Expected Time of Completion
Will be done by today, 22:00 IST

### Reason for Delay
Had been away from my machine due to vacations. My sincerest apologies for the delay.
